version: "3"

services:
### MySql  ################################################
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT_CONTAINER}"
    volumes:
      - ${MYSQL_VOLUMEN_PATH}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_NAME: ${MYSQL_SERVICE_NAME}
      SERVICE_TAGS: ${MYSQL_SERVICE_TAGS}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
